/** Dual-niche support: psychology/neuroscience or ambient/meditation */
export type Niche = 'psychology' | 'ambient';

/** Video idea generated by AI */
export interface VideoIdea {
  id?: string;
  title: string;
  hook: string;
  targetAudience: string;
  whyItWorks: string;
  searchVolume: 'High' | 'Medium' | 'Rising Trend';
  primaryKeyword: string;
  secondaryKeywords: string[];
  niche: Niche;
  createdAt?: string;
}
