/** Dual-niche support: psychology/neuroscience or ambient/meditation */
export type Niche = 'psychology' | 'ambient';

/** Video idea generated by AI */
export interface VideoIdea {
  id?: string;
  title: string;
  hook: string;
  targetAudience: string;
  whyItWorks: string;
  searchVolume: 'High' | 'Medium' | 'Rising Trend';
  primaryKeyword: string;
  secondaryKeywords: string[];
  niche: Niche;
  createdAt?: string;
}

/** Full video plan generated by AI (markdown) */
export interface VideoPlan {
  id?: string;
  ideaId?: string;
  title: string;
  markdown: string;
  niche: Niche;
  createdAt?: string;
}

/** Channel branding generated by AI */
export interface ChannelBranding {
  channelNames: string[];
  seoDescription: string;
  avatarPrompt: string;
  bannerPrompt: string;
}
