import type { Niche } from './Niche.js';

/** Video idea generated by AI */
export interface VideoIdea {
  id?: string;
  userId?: string;
  title: string;
  hook: string;
  targetAudience: string;
  whyItWorks: string;
  searchVolume: 'High' | 'Medium' | 'Rising Trend';
  primaryKeyword: string;
  secondaryKeywords: string[];
  niche: Niche;
  createdAt?: Date;
}
